# Generated by Django 4.2.1 on 2025-03-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="human",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=255),
        ),
    ]
