# Generated by Django 4.2.1 on 2025-03-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human", "0002_human_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="human",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
