# Generated by Django 4.2.1 on 2025-03-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human", "0003_alter_human_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="human",
            options={"ordering": ["-time_create"]},
        ),
        migrations.AlterField(
            model_name="human",
            name="is_published",
            field=models.BooleanField(
                choices=[(0, "не опубликован"), (1, "Опубликован")], default=0
            ),
        ),
        migrations.AddIndex(
            model_name="human",
            index=models.Index(
                fields=["-time_create"], name="human_human_time_cr_b14f92_idx"
            ),
        ),
    ]
