# Generated by Django 4.2.1 on 2025-03-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human", "0005_category_human_cat"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="human",
            name="tags",
            field=models.ManyToManyField(blank=True, to="human.tagpost"),
        ),
    ]
