# Generated by Django 4.2.1 on 2025-03-17 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("human", "0006_tagpost_human_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Husband",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="human",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to="human.tagpost"
            ),
        ),
        migrations.AddField(
            model_name="human",
            name="husband",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="human.husband",
            ),
        ),
    ]
