# Generated by Django 4.2.1 on 2025-03-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human", "0008_alter_human_husband_alter_human_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="human",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
